### ISSUE TITLE
Undefined reference to aligned_alloc on Win7 MSYS+Vulkan

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [glfw/glfw#727]
I'm in a Windows 7 64-bit system with MinGW, MSYS, Nvidia Vulkan drivers.

Current revision: 89f438de5a862802717a5d6e32ebfe462775cccf

Cmake:

```
cmake -G "MSYS Makefiles" -D BUILD_SHARED_LIBS=ON -D VULKAN_INCLUDE_DIR=/c/MinGW/include/vulkan/ ..
```

Make:

```
Scanning dependencies of target vulkan
[ 96%] Building C object tests/CMakeFiles/vulkan.dir/vulkan.c.obj
c:/Users/Colonel/Downloads/glfw/tests/vulkan.c: In function 'myalloc':
c:/Users/Colonel/Downloads/glfw/tests/vulkan.c:1671:5: warning: return makes pointer from integer without a cast
     return aligned_alloc(alignment, size);
     ^
Linking C executable vulkan.exe
Warning: resolving _vkEndCommandBuffer@4 by linking to _vkEndCommandBuffer
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
Warning: resolving _vkQueueSubmit@20 by linking to _vkQueueSubmit
Warning: resolving _vkQueueWaitIdle@4 by linking to _vkQueueWaitIdle
Warning: resolving _vkFreeCommandBuffers@20 by linking to _vkFreeCommandBuffers
Warning: resolving _vkAllocateCommandBuffers@12 by linking to _vkAllocateCommandBuffers
// ...many similar messages...
Warning: resolving _vkDestroyDevice@8 by linking to _vkDestroyDevice
Warning: resolving _vkDestroySurfaceKHR@16 by linking to _vkDestroySurfaceKHR
Warning: resolving _vkDestroyInstance@8 by linking to _vkDestroyInstance
CMakeFiles/vulkan.dir/objects.a(vulkan.c.obj):vulkan.c:(.text+0x37bb): undefined reference to `aligned_alloc'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [tests/vulkan.exe] Error 1
make[1]: *** [tests/CMakeFiles/vulkan.dir/all] Error 2
make: *** [all] Error 2
```

The warnings happen when doing anything with Vulkan functions with MinGW, but Vulkan still works. However, it seems that `aligned_alloc` isn't implemented.

Since the files are being built to `./tests/`, I'm assuming that these are just tests that I can ignore, right?

**Comment by elmindreda** [comment]
The Vulkan loader import library is intended for Visual C++, which is causing the error. I don't know offhand how to resolve this and I don't have time to look into it right now. Sorry.

Yes, the tests directory can be safely ignored.

**Comment by elmindreda** [comment]
You can create a compatible import library for the Vulkan loader DLL with [dlltool](http://www.mingw.org/wiki/dlltool) or (probably) link against it directly since the MinGW tools are smarter about that sort of thing.

**Comment by Delwin9999** [comment]
This is also a problem on Linux builds with GLIBC older than 2.16
