### PR TITLE
Fix build on Mac OS X 10.7 Lion.

### LINKED ISSUE #157: Build error with 10.7 SDK
Linking against the 10.7 SDK (CMAKE_OSX_SYSROOT /Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk) instead of the 10.8 SDK produces the following compilation error:

<pre>
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:97:45: error: unknown type name 'CVDisplayLinkRef'; did you mean 'CGDisplayModeRef'?
                                            CVDisplayLinkRef link)
                                            ^~~~~~~~~~~~~~~~
                                            CGDisplayModeRef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:17:31: note: 
      'CGDisplayModeRef' declared here
typedef struct CGDisplayMode *CGDisplayModeRef;
                              ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:106:29: warning: implicit declaration of function
      'CVDisplayLinkGetNominalOutputVideoRefreshPeriod' is invalid in C99 [-Wimplicit-function-declaration]
        const CVTime time = CVDisplayLinkGetNominalOutputVideoRefreshPeriod(link);
                            ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:106:22: error: initializing 'const CVTime' with an expression of incompatible type 'int'
        const CVTime time = CVDisplayLinkGetNominalOutputVideoRefreshPeriod(link);
                     ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:344:5: error: unknown type name 'CVDisplayLinkRef'; did you mean 'CGDisplayModeRef'?
    CVDisplayLinkRef link;
    ^~~~~~~~~~~~~~~~
    CGDisplayModeRef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:17:31: note: 
      'CGDisplayModeRef' declared here
typedef struct CGDisplayMode *CGDisplayModeRef;
                              ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:346:5: warning: implicit declaration of function 'CVDisplayLinkCreateWithCGDisplay' is
      invalid in C99 [-Wimplicit-function-declaration]
    CVDisplayLinkCreateWithCGDisplay(monitor->ns.displayID, &link);
    ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:368:5: warning: implicit declaration of function 'CVDisplayLinkRelease' is invalid in C99
      [-Wimplicit-function-declaration]
    CVDisplayLinkRelease(link);
    ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:375:5: error: use of undeclared identifier 'CVDisplayLinkRef'; did you mean
      'CVDisplayLinkRelease'?
    CVDisplayLinkRef link;
    ^~~~~~~~~~~~~~~~
    CVDisplayLinkRelease
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:368:5: note: 'CVDisplayLinkRelease' declared here
    CVDisplayLinkRelease(link);
    ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:375:21: error: expected ';' after expression
    CVDisplayLinkRef link;
                    ^
                    ;
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:380:51: warning: incompatible pointer types passing 'int (const char *, const char *)' to
      parameter of type 'CGDisplayModeRef' (aka 'struct CGDisplayMode *') [-Wincompatible-pointer-types]
    *mode = vidmodeFromCGDisplayMode(displayMode, link);
                                                  ^~~~
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:97:62: note: passing argument to parameter 'link' here
                                            CVDisplayLinkRef link)
                                                             ^
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:375:5: warning: expression result unused [-Wunused-value]
    CVDisplayLinkRef link;
    ^~~~~~~~~~~~~~~~
/Users/sephirok/Documents/glfw/src/cocoa_monitor.m:375:22: warning: expression result unused [-Wunused-value]
    CVDisplayLinkRef link;
                     ^~~~
</pre>

### PR DESCRIPTION
**Pull request by metajack**
`CVDisplayLinkRef` needs an extra header file, and `NSAppKitVersionNumber10_7`
wasn't added until 10.8so use `> NSAppKitVersionNumber10_6` instead.

Fixes #157

### CODE REVIEW

**Comment by barracuda156** [comment]
Still failed on 10.6 though.

**Comment by elmindreda** [comment]
@barracuda156 GLFW doesn't support 10.6 and hasn't for a while now. Even though a lot of Apple's hardware lives forever, their APIs don't.

**Comment by barracuda156** [comment]
@elmindreda Yeah I figured out I need to fallback to a somewhat earlier version.
