### ISSUE TITLE
VS CODE + GO + GLFW + DELVE CANT COMPILE

### ISSUE THREAD

**Issue by MrLiet** [glfw/glfw#896]
Hello.

I have a problem:

![image](https://cloud.githubusercontent.com/assets/23429917/20244303/9d7a465c-a9ae-11e6-8e94-2a7773b65bd2.png)

Source code:

```
package main

import "github.com/go-gl/glfw/v3.2/glfw"

func main() {

	glfw.Init()

	w, _ := glfw.CreateWindow(800, 600, "hello", nil, nil)
	var running bool = true
	for running {
		glfw.PollEvents()
		if w.ShouldClose() {
			running = false
		}
	}

}

```

Console output:

> # me/proj1
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> exit status 2
> 

Im use:
Windows 64 bit
Go 1.7.3
Mingw 64
VS Code

VS Code settings:
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave":false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true, 
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.gocodeAutoBuild": false,
    "go.autocompleteUnimportedPackages": true
    
    
}

and Launch settings:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}

Help!

**Comment by MrLiet** [comment]
And it's work fine with glfw 3.1 version
![image](https://cloud.githubusercontent.com/assets/23429917/20244672/7f5d10aa-a9bd-11e6-91d3-d8554077ea11.png)

**Comment by elmindreda** [comment]
Ping @shurcooL.

**Comment by shurcooL** [comment]
@MrLiet, this is the wrong issue tracker to report this issue. It seems to be completely related to the Go bindings for GLFW, not GLFW the C library itself. You should report it at:

https://github.com/go-gl/glfw/issues
