### ISSUE TITLE
Building from source on Catalina

### ISSUE THREAD

**Issue by msken** [glfw/glfw#1838]
Failed to compile with Xcode 12.3 configured with CMake 3.19.0.
What is the problem, and how can I work around?

[  1%] Building C object src/CMakeFiles/glfw.dir/cocoa_init.m.o
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:79:5: error: use of undeclared
      identifier 'NSString'; did you mean 'cString'?
    NSString* appName = nil;
    ^~~~~~~~
    cString
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/OpenScripting.framework/Headers/ASRegistry.h:212:3: note: 
      'cString' declared here
  cString                       = cStringClass /* old name for cStringCl...
  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:79:15: error: use of undeclared
      identifier 'appName'; did you mean 'pName'?
    NSString* appName = nil;
              ^~~~~~~
              pName
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AERegistry.h:478:3: note: 
      'pName' declared here
  pName                         = 'pnam' /*  0x706e616d  */
  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:79:23: error: expression is not
      assignable
    NSString* appName = nil;
    ~~~~~~~~~~~~~~~~~ ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:80:5: error: use of undeclared
      identifier 'NSDictionary'; did you mean 'UseDictionary'?
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
    ^~~~~~~~~~~~
    UseDictionary
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/SpeechSynthesis.framework/Headers/SpeechSynthesis.h:1504:1: note: 
      'UseDictionary' declared here
UseDictionary(
^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:80:5: warning: 'UseDictionary' is
      deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/SpeechSynthesis.framework/Headers/SpeechSynthesis.h:1504:1: note: 
      'UseDictionary' has been explicitly marked deprecated here
UseDictionary(
^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:80:19: error: use of undeclared
      identifier 'bundleInfo'
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
                  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:80:32: error: expected expression
    NSDictionary* bundleInfo = [[NSBundle mainBundle] infoDictionary];
                               ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:81:5: error: use of undeclared
      identifier 'NSString'; did you mean 'cString'?
    NSString* nameKeys[] =
    ^~~~~~~~
    cString
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/OpenScripting.framework/Headers/ASRegistry.h:212:3: note: 
      'cString' declared here
  cString                       = cStringClass /* old name for cStringCl...
  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:81:24: error: expected expression
    NSString* nameKeys[] =
                       ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:81:15: error: use of undeclared
      identifier 'nameKeys'
    NSString* nameKeys[] =
              ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:82:5: error: expected expression
    {
    ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:90:29: error: use of undeclared
      identifier 'nameKeys'
    for (i = 0;  i < sizeof(nameKeys) / sizeof(nameKeys[0]);  i++)
                            ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:90:48: error: use of undeclared
      identifier 'nameKeys'
    for (i = 0;  i < sizeof(nameKeys) / sizeof(nameKeys[0]);  i++)
                                               ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:92:30: error: use of undeclared
      identifier 'nameKeys'
        id name = bundleInfo[nameKeys[i]];
                             ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:92:19: error: use of undeclared
      identifier 'bundleInfo'
        id name = bundleInfo[nameKeys[i]];
                  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:94:13: error: expected expression
            [name isKindOfClass:[NSString class]] &&
            ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:97:13: error: use of undeclared
      identifier 'appName'
            appName = name;
            ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:102:10: error: use of undeclared
      identifier 'appName'; did you mean 'pName'?
    if (!appName)
         ^~~~~~~
         pName
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AERegistry.h:478:3: note: 
      'pName' declared here
  pName                         = 'pnam' /*  0x706e616d  */
  ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:106:13: error: use of undeclared
      identifier 'appName'
            appName = @(*progname);
            ^
/Users/xxx/git/glfw-3.3.2/src/cocoa_init.m:106:23: error: expected
      expression
            appName = @(*progname);
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[2]: *** [src/CMakeFiles/glfw.dir/cocoa_init.m.o] Error 1
make[1]: *** [src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

**Comment by msken** [comment]
The following information helped me.
Please update third-party/glfw/src/CMakeLists.txt

https://gitmemory.com/issue/wjakob/nori/20/762714986
